Repository Pive-Guyz/ondam-frontend, pull requests merged in 2025-04, with the labels that each got.

#1 [feat] 회원 로그인 기능 + 메인화면 + 다이어리 화면
  package-lock.json
  package.json
  src/App.vue
  src/components/modal/DiaryModal.vue
  src/components/modal/LoginModal.vue
  src/components/modal/WriteDiaryModal.vue
  src/main.js
  src/router/index.js
  src/stores/auth.js
  src/views/DiaryPage.vue
  src/views/MainPage.vue
  src/views/StartPage.vue
Labels: :sparkles: enhancement

#2 [chore] API 연동 관련
  package-lock.json
  package.json
  postcss.config.js
  src/App.vue
  src/api/config/axios.js
  src/api/counseleeCommand.js
  src/api/counseleeQuery.js
  src/assets/main.css
  src/assets/vue.svg
  src/components/HelloWorld.vue
  src/main.js
  src/models/Counselee.js
  src/router/index.js
  src/style.css
  src/views/CounseleePage.vue
  src/views/MainPage.vue
  tailwind.config.js
  vite.config.js
Labels: :sparkles: enhancement

#3 feat: 다이어리에서 오늘 받은 일기 조회 기능 구현 / refractor: vuetify로 스타일 형식 변경
  package-lock.json
  package.json
  src/components/modal/DiaryModal.vue
  src/components/modal/LoginModal.vue
  src/components/modal/ReceivedDiaryModal.vue
  src/components/modal/ReplyModal.vue
  src/main.js
  src/plugins/vuetify.js
  src/router/index.js
  src/views/DiaryPage.vue
  src/views/MainPage.vue
  src/views/ReceivedDiaryPage.vue
  src/views/StartPage.vue
Labels: 🎨 design, :sparkles: enhancement, 🔧 refactoring

#9 [feat] 오늘의 일기를 받은 뒤에 답장 기능 구현
  package-lock.json
  src/components/modal/ReceivedDiaryModal.vue
  src/components/modal/ReplyModal.vue
  src/views/ReceivedDiaryPage.vue
  src/views/StartPage.vue
Labels: :sparkles: enhancement

#10 [feat] 상담 등록 API 연동(상담자ID, 내담자ID는 하드코딩, 페이지 이동X)
  package-lock.json
  package.json
  src/App.vue
  src/api/counsel/counselCommand.js
  src/api/counsel/counselQuery.js
  src/api/counselee/counseleeCommand.js
  src/api/counselee/counseleeQuery.js
  src/models/Counsel.js
  src/plugins/vuetify.js
  src/router/index.js
  src/views/CounseleeCounselPage.vue
  src/views/CounseleePage.vue
  src/views/CounslingLogFormPage.vue
Labels: :sparkles: enhancement, 🔧 refactoring

#13 [feat] 삭제된 일기 / 답장 미조회 구현
  src/components/modal/DiaryModal.vue
  src/components/modal/MyReplyModal.vue
  src/components/modal/ReceivedDiaryModal.vue
  src/components/modal/ReplyModal.vue
  src/router/index.js
  src/views/DiaryPage.vue
  src/views/MyReplyListPage.vue
  src/views/ReceivedDiaryPage.vue
Labels: :sparkles: enhancement

#14 [feat] 상담 일지 페이지 구현 및 BE 연동
  package-lock.json
  package.json
  src/components/analysis/CounselSummary.vue
  src/components/analysis/EffectiveStatement.vue
  src/components/analysis/EmotionAnalysis.vue
  src/components/analysis/TroubleSummary.vue
  src/components/common/Sidebar.vue
  src/main.js
  src/plugins/vuetify.js
  src/router/index.js
  src/views/counsel/CounselingReport.vue
Labels: 🎨 design, :sparkles: enhancement

#17 [test] gpt 분석 401 에러 확인
  src/api/analysis/analysisCommand.js
  src/components/form/FormLabel.vue
  src/router/index.js
  src/utils/formatter.js
  src/utils/inputUtils.js
  src/views/CounseleeCounselPage.vue
  src/views/CounseleePage.vue
  src/views/CounseleeRegisterPage.vue
  src/views/CounselingReport.vue
  src/views/CounslingLogFormPage.vue
Labels: :sparkles: enhancement, :test_tube: test

#26 [refactor] 상담 일지에서 api 호출하는 방식 수정
  src/api/analysis/analysisQuery.js
  src/views/CounselingReport.vue
Labels: 🔧 refactoring

#28 [refactor] api 형식 통일(일기 도메인)
  src/api/diary/diaryCommand.js
  src/api/diary/diaryRecordCommand.js
  src/api/diary/replyCommand.js
  src/components/modal/DiaryModal.vue
  src/components/modal/MyReplyModal.vue
  src/components/modal/ReceivedDiaryModal.vue
  src/components/modal/ReplyModal.vue
  src/components/modal/WriteDiaryModal.vue
  src/views/DiaryPage.vue
  src/views/MyReplyListPage.vue
  src/views/ReceivedDiaryPage.vue
  src/views/StartPage.vue
Labels: 🔧 refactoring

#20 [feat] 일기/답장 신고 기능 구현
  src/api/report/reportCommand.js
  src/components/modal/DiaryModal.vue
  src/components/modal/ReceivedDiaryModal.vue
  src/components/report/DiaryReportModal.vue
  src/components/report/ReplyReportModal.vue
Labels: :sparkles: enhancement

#30 [feat] 멤버 사이드바 추가
  src/components/sidebar/MemberSidebar.vue
  src/views/CounseleePage.vue
  src/views/CounselingReport.vue
  src/views/CounslingLogFormPage.vue
  src/views/MyPage.vue
Labels: 🎨 design, :sparkles: enhancement

#31 [feat] 메인 페이지 수정
  src/components/main/LandingSection.vue
  src/resources/analysis/emotion_analysis.png
  src/resources/analysis/emotion_analysis_bar_chart.png
  src/resources/analysis/emotion_analysis_pie_chart.png
  src/resources/analysis/problem_summary.png
  src/resources/counsel/counsel_log.png
  src/resources/counsel/counsels.png
  src/resources/counselee/counselees.png
  src/views/MainPage.vue
Labels: 🎨 design, :sparkles: enhancement
