Repository Pive-Guyz/ondam-frontend, pull requests merged in 2025-05, with the labels that each got.

#29 [feat] 시작페이지 api추가
  src/api/member/memberCommand.js
  src/api/member/memberQuery.js
  src/views/MemberList.vue
  src/views/SignUpPage.vue
  src/views/StartPage.vue
Labels: :sparkles: enhancement

#32 [feat]포인트 기능 구현 + 로그인 기능 구현
  src/assets/img/pencilMan.jpeg
  src/components/modal/ReceivedDiaryModal.vue
  src/components/modal/ReplyModal.vue
  src/components/modal/WriteDiaryModal.vue
  src/stores/auth.js
  src/views/DiaryPage.vue
  src/views/MyReplyListPage.vue
  src/views/ReceivedDiaryPage.vue
  src/views/StartPage.vue
Labels: :sparkles: enhancement

#34 [refactor] 신고 관련 페이지 및 모달 구현
  src/api/report/reportCommand.js
  src/api/report/reportQuery.js
  src/components/report/ContentModal.vue
  src/components/report/List.vue
  src/components/report/ReportCard.vue
  src/components/report/ReportDetailModal.vue
  src/utils/reportUtils.js
Labels: 🔧 refactoring

#36 [feat] Header/Footer 생성 및 메인페이지 연결
  src/components/Footer.vue
  src/components/Header.vue
  src/views/MainPage.vue
Labels: :sparkles: enhancement

#40 [refactor] 헤더 및 사이드바 수정
  src/components/Header.vue
  src/components/sidebar/AdminSidebar.vue
  src/components/sidebar/MemberSidebar.vue
Labels: 🔧 refactoring

#42 [refractor] 일기 도메인 사이드바 적용
  src/components/modal/DiaryModal.vue
  src/components/modal/ReceivedDiaryModal.vue
  src/views/DiaryPage.vue
  src/views/MyReplyListPage.vue
  src/views/ReceivedDiaryPage.vue
Labels: :sparkles: enhancement

#44 [feat] 로그아웃 알림창 / [refactor] 로그인화면 재수정(롤백된듯함), 헤더 회원이름 표시, 일기 신고 시 모달창 재구현
  src/components/Header.vue
  src/components/modal/ReceivedDiaryModal.vue
  src/stores/auth.js
  src/views/StartPage.vue
Labels: 🔧 refactoring

#46 [refactor] 신고 시 답장 id 저장 오류 해결
  src/components/report/ReplyReportModal.vue
Labels: 🔧 refactoring

#48 [feat] 회원 화면 구현
  src/components/member/ChangePasswordModal.vue
  src/components/member/ConfirmWithdrawalModal.vue
  src/components/member/RoleChangeModal.vue
  src/views/AdminPage.vue
  src/views/MyPage.vue
  src/views/SignUpPage.vue
  src/views/StartPage.vue
Labels: :sparkles: enhancement

#50 [refactor] 신고 목록 조회 페이지 헤더 추가
  src/views/ReportPage.vue
Labels: 🔧 refactoring

#54 [refactor] 헤더 로고 클릭 시 메인페이지로 이동
  src/components/Header.vue
Labels: 🔧 refactoring

#57 [refractor] 다이어리 페이지 라우터 변경(홈으로 돌아가기)
  src/views/DiaryPage.vue
Labels: 🔧 refactoring

#55 [feat] auth 적용/ 프로필이미지 URL처리/ 정보수정 readonly로 변경
  src/api/member/memberQuery.js
  src/stores/auth.js
  src/views/AdminPage.vue
  src/views/MyPage.vue
  src/views/SignUpPage.vue
  src/views/StartPage.vue
Labels: :sparkles: enhancement

#59 [refactor] 헤더 버튼 이동 경로 수정
  src/components/Header.vue
Labels: 🔧 refactoring

#62 [feat] 로그아웃시 메인페이지로 이동, [refractor] 모달 창 닫힌 후 기능 부작동 수정
  src/components/modal/DiaryModal.vue
  src/components/modal/MyReplyModal.vue
  src/components/modal/ReceivedDiaryModal.vue
  src/components/modal/ReplyModal.vue
  src/components/modal/WriteDiaryModal.vue
  src/views/DiaryPage.vue
  src/views/ReceivedDiaryPage.vue
Labels: :bug: bug, :sparkles: enhancement

#63 [hotfix] MemberSideBar의 파일명과 import from path 통일
  src/views/CounseleeRegisterPage.vue
Labels: 🚨 HOTFIX

#65 [refactor] 프로필 사진 경로 수정 / 회원 세부 정보에 프로필 사진 등록
  src/api/member/memberCommand.js
  src/components/member/MemberDetailModal.vue
  src/components/sidebar/AdminSidebar.vue
  src/views/AdminPage.vue
  src/views/MemberList.vue
  src/views/MyPage.vue
  src/views/SignUpPage.vue
Labels: 🔧 refactoring
